---
- name: Update camera config
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^start_x=', line: 'start_x=1' }
    - { regexp: '^gpu_mem=', line: 'gpu_mem=128' }

- name: Disable camera led
  lineinfile:
    dest: /boot/config.txt
    regexp: "^disable_camera_led="
    line: "disable_camera_led=1"
  when: disable_camera_led

- name: Enable camera led
  lineinfile:
    dest: /boot/config.txt
    regexp: "^disable_camera_led="
    line: "disable_camera_led=0"
  when: disable_camera_led == false

# - name: Add bcm2835 module
#   modprobe:
#     name: bcm2835-v4l2
#     state: present

- name: Add bcm2835 module
  lineinfile:
    dest: /etc/modules
    regexp: "^bcm2835-v4l2"
    line: "bcm2835-v4l2"

- name: Install rpi-source
  changed_when: false
  shell: sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - bc
    - libncurses5-dev
    - ffmpeg

- name: Install kernel source
  changed_when: false
  shell: rpi-source
  
- name: Install v4l2loopback
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - v4l2loopback-dkms

- name: Add v4l2loopback module
  lineinfile:
    dest: /etc/modules
    regexp: "^v4l2loopback"
    line: "v4l2loopback"

- name: Add v4l2loopback module configuration
  copy:
    content: "options v4l2loopback video_nr=1"
    dest: /etc/modprobe.d/v4l2loopback.conf